[project]
name = "paligemma-from-scratch"
version = "0.1.0"
description = "PaliGemma From Scratch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "pillow>=12.1.0",
    "torch>=2.7.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
